/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package play;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {

}
